//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace kurema.Epub.Xml.Epub20.Container {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:opendocument:xmlns:container")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:oasis:names:tc:opendocument:xmlns:container", IsNullable=false)]
    public partial class container {
        
        private rootfile[] rootfilesField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("rootfile", IsNullable=false)]
        public rootfile[] rootfiles {
            get {
                return this.rootfilesField;
            }
            set {
                this.rootfilesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:opendocument:xmlns:container")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:oasis:names:tc:opendocument:xmlns:container", IsNullable=false)]
    public partial class rootfile {
        
        private string fullpathField;
        
        private string mediatypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("full-path")]
        public string fullpath {
            get {
                return this.fullpathField;
            }
            set {
                this.fullpathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("media-type")]
        public string mediatype {
            get {
                return this.mediatypeField;
            }
            set {
                this.mediatypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:opendocument:xmlns:container")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:oasis:names:tc:opendocument:xmlns:container", IsNullable=false)]
    public partial class rootfiles {
        
        private rootfile[] rootfileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rootfile")]
        public rootfile[] rootfile {
            get {
                return this.rootfileField;
            }
            set {
                this.rootfileField = value;
            }
        }
    }
}
