//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace kurema.Epub.Xml.Epub20.NcxOld {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.daisy.org/z3986/2005/ncx/", IsNullable=false)]
    public partial class ncx {
        
        private meta[] headField;
        
        private docTitle docTitleField;
        
        private docAuthor[] docAuthorField;
        
        private navMap navMapField;
        
        private pageList pageListField;
        
        private navList[] navListField;
        
        private ncxVersion versionField;
        
        private string langField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("meta", IsNullable=false)]
        public meta[] head {
            get {
                return this.headField;
            }
            set {
                this.headField = value;
            }
        }
        
        /// <remarks/>
        public docTitle docTitle {
            get {
                return this.docTitleField;
            }
            set {
                this.docTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("docAuthor")]
        public docAuthor[] docAuthor {
            get {
                return this.docAuthorField;
            }
            set {
                this.docAuthorField = value;
            }
        }
        
        /// <remarks/>
        public navMap navMap {
            get {
                return this.navMapField;
            }
            set {
                this.navMapField = value;
            }
        }
        
        /// <remarks/>
        public pageList pageList {
            get {
                return this.pageListField;
            }
            set {
                this.pageListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("navList")]
        public navList[] navList {
            get {
                return this.navListField;
            }
            set {
                this.navListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ncxVersion version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.daisy.org/z3986/2005/ncx/", IsNullable=false)]
    public partial class meta {
        
        private string nameField;
        
        private string contentField;
        
        private string schemeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string scheme {
            get {
                return this.schemeField;
            }
            set {
                this.schemeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.daisy.org/z3986/2005/ncx/", IsNullable=false)]
    public partial class docTitle {
        
        private text textField;
        
        private img imgField;
        
        private string idField;
        
        /// <remarks/>
        public text text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public img img {
            get {
                return this.imgField;
            }
            set {
                this.imgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.daisy.org/z3986/2005/ncx/", IsNullable=false)]
    public partial class text {
        
        private string idField;
        
        private string classField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.daisy.org/z3986/2005/ncx/", IsNullable=false)]
    public partial class img {
        
        private string idField;
        
        private string classField;
        
        private string srcField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string src {
            get {
                return this.srcField;
            }
            set {
                this.srcField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.daisy.org/z3986/2005/ncx/", IsNullable=false)]
    public partial class docAuthor {
        
        private text textField;
        
        private img imgField;
        
        private string idField;
        
        /// <remarks/>
        public text text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public img img {
            get {
                return this.imgField;
            }
            set {
                this.imgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.daisy.org/z3986/2005/ncx/", IsNullable=false)]
    public partial class navMap {
        
        private navInfo[] navInfoField;
        
        private navLabel[] navLabelField;
        
        private navPoint[] navPointField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("navInfo")]
        public navInfo[] navInfo {
            get {
                return this.navInfoField;
            }
            set {
                this.navInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("navLabel")]
        public navLabel[] navLabel {
            get {
                return this.navLabelField;
            }
            set {
                this.navLabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("navPoint")]
        public navPoint[] navPoint {
            get {
                return this.navPointField;
            }
            set {
                this.navPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.daisy.org/z3986/2005/ncx/", IsNullable=false)]
    public partial class navInfo {
        
        private text textField;
        
        private img imgField;
        
        /// <remarks/>
        public text text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public img img {
            get {
                return this.imgField;
            }
            set {
                this.imgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.daisy.org/z3986/2005/ncx/", IsNullable=false)]
    public partial class navLabel {
        
        private text textField;
        
        private img imgField;
        
        /// <remarks/>
        public text text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public img img {
            get {
                return this.imgField;
            }
            set {
                this.imgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.daisy.org/z3986/2005/ncx/", IsNullable=false)]
    public partial class navPoint {
        
        private navLabel[] navLabelField;
        
        private content contentField;
        
        private navPoint[] navPoint1Field;
        
        private string idField;
        
        private string classField;
        
        private string playOrderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("navLabel")]
        public navLabel[] navLabel {
            get {
                return this.navLabelField;
            }
            set {
                this.navLabelField = value;
            }
        }
        
        /// <remarks/>
        public content content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("navPoint")]
        public navPoint[] navPoint1 {
            get {
                return this.navPoint1Field;
            }
            set {
                this.navPoint1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string playOrder {
            get {
                return this.playOrderField;
            }
            set {
                this.playOrderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.daisy.org/z3986/2005/ncx/", IsNullable=false)]
    public partial class content {
        
        private string idField;
        
        private string srcField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string src {
            get {
                return this.srcField;
            }
            set {
                this.srcField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.daisy.org/z3986/2005/ncx/", IsNullable=false)]
    public partial class pageList {
        
        private navInfo[] navInfoField;
        
        private navLabel[] navLabelField;
        
        private pageTarget[] pageTargetField;
        
        private string idField;
        
        private string classField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("navInfo")]
        public navInfo[] navInfo {
            get {
                return this.navInfoField;
            }
            set {
                this.navInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("navLabel")]
        public navLabel[] navLabel {
            get {
                return this.navLabelField;
            }
            set {
                this.navLabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pageTarget")]
        public pageTarget[] pageTarget {
            get {
                return this.pageTargetField;
            }
            set {
                this.pageTargetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.daisy.org/z3986/2005/ncx/", IsNullable=false)]
    public partial class pageTarget {
        
        private navLabel[] navLabelField;
        
        private content contentField;
        
        private string idField;
        
        private string valueField;
        
        private pageTargetType typeField;
        
        private string classField;
        
        private string playOrderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("navLabel")]
        public navLabel[] navLabel {
            get {
                return this.navLabelField;
            }
            set {
                this.navLabelField = value;
            }
        }
        
        /// <remarks/>
        public content content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public pageTargetType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string playOrder {
            get {
                return this.playOrderField;
            }
            set {
                this.playOrderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
    public enum pageTargetType {
        
        /// <remarks/>
        front,
        
        /// <remarks/>
        normal,
        
        /// <remarks/>
        special,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.daisy.org/z3986/2005/ncx/", IsNullable=false)]
    public partial class navList {
        
        private navInfo[] navInfoField;
        
        private navLabel[] navLabelField;
        
        private navTarget[] navTargetField;
        
        private string idField;
        
        private string classField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("navInfo")]
        public navInfo[] navInfo {
            get {
                return this.navInfoField;
            }
            set {
                this.navInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("navLabel")]
        public navLabel[] navLabel {
            get {
                return this.navLabelField;
            }
            set {
                this.navLabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("navTarget")]
        public navTarget[] navTarget {
            get {
                return this.navTargetField;
            }
            set {
                this.navTargetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.daisy.org/z3986/2005/ncx/", IsNullable=false)]
    public partial class navTarget {
        
        private navLabel[] navLabelField;
        
        private content contentField;
        
        private string idField;
        
        private string classField;
        
        private string valueField;
        
        private string playOrderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("navLabel")]
        public navLabel[] navLabel {
            get {
                return this.navLabelField;
            }
            set {
                this.navLabelField = value;
            }
        }
        
        /// <remarks/>
        public content content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string playOrder {
            get {
                return this.playOrderField;
            }
            set {
                this.playOrderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
    public enum ncxVersion {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2005-1")]
        Item20051,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.daisy.org/z3986/2005/ncx/", IsNullable=false)]
    public partial class head {
        
        private meta[] metaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("meta")]
        public meta[] meta {
            get {
                return this.metaField;
            }
            set {
                this.metaField = value;
            }
        }
    }
}
