//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// このソース コードは xsd によって自動生成されました。Version=4.8.3928.0 です。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.idpf.org/2007/opf")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.idpf.org/2007/opf", IsNullable=false)]
public partial class package : opfpackagecontent {
    
    private packageVersion versionField;
    
    private string uniqueidentifierField;
    
    private string idField;
    
    private string prefixField;
    
    private string langField;
    
    private opfcollectionmetadatacontentMetaDir dirField;
    
    private bool dirFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public packageVersion version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("unique-identifier", DataType="NCName")]
    public string uniqueidentifier {
        get {
            return this.uniqueidentifierField;
        }
        set {
            this.uniqueidentifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string prefix {
        get {
            return this.prefixField;
        }
        set {
            this.prefixField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public opfcollectionmetadatacontentMetaDir dir {
        get {
            return this.dirField;
        }
        set {
            this.dirField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dirSpecified {
        get {
            return this.dirFieldSpecified;
        }
        set {
            this.dirFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.idpf.org/2007/opf")]
public enum packageVersion {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3.0")]
    Item30,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.idpf.org/2007/opf")]
public enum opfcollectionmetadatacontentMetaDir {
    
    /// <remarks/>
    ltr,
    
    /// <remarks/>
    rtl,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="opf.package.content", Namespace="http://www.idpf.org/2007/opf")]
public partial class opfpackagecontent {
    
    private opfpackagecontentMetadata metadataField;
    
    private manifest manifestField;
    
    private spine spineField;
    
    private reference[] guideField;
    
    private mediaType[] bindingsField;
    
    private collection[] collectionField;
    
    /// <remarks/>
    public opfpackagecontentMetadata metadata {
        get {
            return this.metadataField;
        }
        set {
            this.metadataField = value;
        }
    }
    
    /// <remarks/>
    public manifest manifest {
        get {
            return this.manifestField;
        }
        set {
            this.manifestField = value;
        }
    }
    
    /// <remarks/>
    public spine spine {
        get {
            return this.spineField;
        }
        set {
            this.spineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("reference", IsNullable=false)]
    public reference[] guide {
        get {
            return this.guideField;
        }
        set {
            this.guideField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("mediaType", IsNullable=false)]
    public mediaType[] bindings {
        get {
            return this.bindingsField;
        }
        set {
            this.bindingsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("collection")]
    public collection[] collection {
        get {
            return this.collectionField;
        }
        set {
            this.collectionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.idpf.org/2007/opf")]
public partial class opfpackagecontentMetadata : opfmetadatacontent1 {
    
    private string idField;
    
    private string langField;
    
    private opfcollectionmetadatacontentMetaDir dirField;
    
    private bool dirFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public opfcollectionmetadatacontentMetaDir dir {
        get {
            return this.dirField;
        }
        set {
            this.dirField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dirSpecified {
        get {
            return this.dirFieldSpecified;
        }
        set {
            this.dirFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="opf.metadata.content", Namespace="http://www.idpf.org/2007/opf")]
public partial class opfmetadatacontent1 {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("contributor", typeof(contributor), Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlElementAttribute("coverage", typeof(coverage), Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlElementAttribute("creator", typeof(creator), Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlElementAttribute("date", typeof(date), Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlElementAttribute("description", typeof(description), Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlElementAttribute("format", typeof(format), Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlElementAttribute("identifier", typeof(identifier), Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlElementAttribute("language", typeof(language), Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlElementAttribute("publisher", typeof(publisher), Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlElementAttribute("relation", typeof(relation), Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlElementAttribute("rights", typeof(rights), Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlElementAttribute("source", typeof(source), Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlElementAttribute("subject", typeof(subject), Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlElementAttribute("title", typeof(title), Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlElementAttribute("type", typeof(type), Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlElementAttribute("link", typeof(opfmetadatacontentLink))]
    [System.Xml.Serialization.XmlElementAttribute("meta", typeof(opfmetadatacontentMeta))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://purl.org/dc/elements/1.1/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://purl.org/dc/elements/1.1/", IsNullable=false)]
public partial class contributor {
    
    private string idField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="opf.collection.metadata.content", Namespace="http://www.idpf.org/2007/opf")]
public partial class opfcollectionmetadatacontent {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("contributor", typeof(contributor), Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlElementAttribute("coverage", typeof(coverage), Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlElementAttribute("creator", typeof(creator), Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlElementAttribute("date", typeof(date), Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlElementAttribute("description", typeof(description), Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlElementAttribute("format", typeof(format), Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlElementAttribute("identifier", typeof(identifier), Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlElementAttribute("language", typeof(language), Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlElementAttribute("publisher", typeof(publisher), Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlElementAttribute("relation", typeof(relation), Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlElementAttribute("rights", typeof(rights), Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlElementAttribute("source", typeof(source), Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlElementAttribute("subject", typeof(subject), Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlElementAttribute("title", typeof(title), Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlElementAttribute("type", typeof(type), Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlElementAttribute("link", typeof(opfmetadatacontentLink))]
    [System.Xml.Serialization.XmlElementAttribute("meta", typeof(opfcollectionmetadatacontentMeta))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://purl.org/dc/elements/1.1/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://purl.org/dc/elements/1.1/", IsNullable=false)]
public partial class coverage {
    
    private string idField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://purl.org/dc/elements/1.1/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://purl.org/dc/elements/1.1/", IsNullable=false)]
public partial class creator {
    
    private string idField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://purl.org/dc/elements/1.1/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://purl.org/dc/elements/1.1/", IsNullable=false)]
public partial class date {
    
    private string idField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://purl.org/dc/elements/1.1/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://purl.org/dc/elements/1.1/", IsNullable=false)]
public partial class description {
    
    private string idField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://purl.org/dc/elements/1.1/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://purl.org/dc/elements/1.1/", IsNullable=false)]
public partial class format {
    
    private string idField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://purl.org/dc/elements/1.1/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://purl.org/dc/elements/1.1/", IsNullable=false)]
public partial class identifier {
    
    private string idField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://purl.org/dc/elements/1.1/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://purl.org/dc/elements/1.1/", IsNullable=false)]
public partial class language {
    
    private string idField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="language")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://purl.org/dc/elements/1.1/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://purl.org/dc/elements/1.1/", IsNullable=false)]
public partial class publisher {
    
    private string idField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://purl.org/dc/elements/1.1/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://purl.org/dc/elements/1.1/", IsNullable=false)]
public partial class relation {
    
    private string idField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://purl.org/dc/elements/1.1/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://purl.org/dc/elements/1.1/", IsNullable=false)]
public partial class rights {
    
    private string idField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://purl.org/dc/elements/1.1/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://purl.org/dc/elements/1.1/", IsNullable=false)]
public partial class source {
    
    private string idField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://purl.org/dc/elements/1.1/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://purl.org/dc/elements/1.1/", IsNullable=false)]
public partial class subject {
    
    private string idField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://purl.org/dc/elements/1.1/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://purl.org/dc/elements/1.1/", IsNullable=false)]
public partial class title {
    
    private string idField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://purl.org/dc/elements/1.1/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://purl.org/dc/elements/1.1/", IsNullable=false)]
public partial class type {
    
    private string idField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.idpf.org/2007/opf")]
public partial class opfmetadatacontentLink {
    
    private string hrefField;
    
    private string relField;
    
    private string idField;
    
    private string refinesField;
    
    private string mediatypeField;
    
    private string propertiesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string href {
        get {
            return this.hrefField;
        }
        set {
            this.hrefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKENS")]
    public string rel {
        get {
            return this.relField;
        }
        set {
            this.relField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string refines {
        get {
            return this.refinesField;
        }
        set {
            this.refinesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("media-type")]
    public string mediatype {
        get {
            return this.mediatypeField;
        }
        set {
            this.mediatypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKENS")]
    public string properties {
        get {
            return this.propertiesField;
        }
        set {
            this.propertiesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.idpf.org/2007/opf")]
public partial class opfcollectionmetadatacontentMeta {
    
    private string propertyField;
    
    private string refinesField;
    
    private string idField;
    
    private string schemeField;
    
    private string langField;
    
    private opfcollectionmetadatacontentMetaDir dirField;
    
    private bool dirFieldSpecified;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string property {
        get {
            return this.propertyField;
        }
        set {
            this.propertyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string refines {
        get {
            return this.refinesField;
        }
        set {
            this.refinesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string scheme {
        get {
            return this.schemeField;
        }
        set {
            this.schemeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public opfcollectionmetadatacontentMetaDir dir {
        get {
            return this.dirField;
        }
        set {
            this.dirField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dirSpecified {
        get {
            return this.dirFieldSpecified;
        }
        set {
            this.dirFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="opf.collection.content", Namespace="http://www.idpf.org/2007/opf")]
public partial class opfcollectioncontent {
    
    private opfcollectioncontentMetadata metadataField;
    
    private collection[] collectionField;
    
    private opfcollectioncontentLink[] linkField;
    
    /// <remarks/>
    public opfcollectioncontentMetadata metadata {
        get {
            return this.metadataField;
        }
        set {
            this.metadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("collection")]
    public collection[] collection {
        get {
            return this.collectionField;
        }
        set {
            this.collectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("link")]
    public opfcollectioncontentLink[] link {
        get {
            return this.linkField;
        }
        set {
            this.linkField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.idpf.org/2007/opf")]
public partial class opfcollectioncontentMetadata : opfcollectionmetadatacontent {
    
    private string idField;
    
    private string langField;
    
    private opfcollectionmetadatacontentMetaDir dirField;
    
    private bool dirFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public opfcollectionmetadatacontentMetaDir dir {
        get {
            return this.dirField;
        }
        set {
            this.dirField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dirSpecified {
        get {
            return this.dirFieldSpecified;
        }
        set {
            this.dirFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.idpf.org/2007/opf")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.idpf.org/2007/opf", IsNullable=false)]
public partial class collection : opfcollectioncontent {
    
    private string idField;
    
    private collectionDir dirField;
    
    private bool dirFieldSpecified;
    
    private string langField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public collectionDir dir {
        get {
            return this.dirField;
        }
        set {
            this.dirField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dirSpecified {
        get {
            return this.dirFieldSpecified;
        }
        set {
            this.dirFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.idpf.org/2007/opf")]
public enum collectionDir {
    
    /// <remarks/>
    ltr,
    
    /// <remarks/>
    rtl,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.idpf.org/2007/opf")]
public partial class opfcollectioncontentLink {
    
    private string hrefField;
    
    private string relField;
    
    private string idField;
    
    private string mediatypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string href {
        get {
            return this.hrefField;
        }
        set {
            this.hrefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKENS")]
    public string rel {
        get {
            return this.relField;
        }
        set {
            this.relField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("media-type")]
    public string mediatype {
        get {
            return this.mediatypeField;
        }
        set {
            this.mediatypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="opf.spine.content", Namespace="http://www.idpf.org/2007/opf")]
public partial class opfspinecontent {
    
    private itemref[] itemrefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("itemref")]
    public itemref[] itemref {
        get {
            return this.itemrefField;
        }
        set {
            this.itemrefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.idpf.org/2007/opf")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.idpf.org/2007/opf", IsNullable=false)]
public partial class itemref {
    
    private itemrefLinear linearField;
    
    private bool linearFieldSpecified;
    
    private string idField;
    
    private string propertiesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public itemrefLinear linear {
        get {
            return this.linearField;
        }
        set {
            this.linearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool linearSpecified {
        get {
            return this.linearFieldSpecified;
        }
        set {
            this.linearFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKENS")]
    public string properties {
        get {
            return this.propertiesField;
        }
        set {
            this.propertiesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.idpf.org/2007/opf")]
public enum itemrefLinear {
    
    /// <remarks/>
    yes,
    
    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="opf.manifest.content", Namespace="http://www.idpf.org/2007/opf")]
public partial class opfmanifestcontent {
    
    private item[] itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("item")]
    public item[] item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.idpf.org/2007/opf")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.idpf.org/2007/opf", IsNullable=false)]
public partial class item {
    
    private string fallbackField;
    
    private string mediaoverlayField;
    
    private string propertiesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string fallback {
        get {
            return this.fallbackField;
        }
        set {
            this.fallbackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("media-overlay", DataType="NCName")]
    public string mediaoverlay {
        get {
            return this.mediaoverlayField;
        }
        set {
            this.mediaoverlayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKENS")]
    public string properties {
        get {
            return this.propertiesField;
        }
        set {
            this.propertiesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.idpf.org/2007/opf")]
public partial class opfmetadatacontentMeta {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.idpf.org/2007/opf")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.idpf.org/2007/opf", IsNullable=false)]
public partial class manifest : opfmanifestcontent {
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.idpf.org/2007/opf")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.idpf.org/2007/opf", IsNullable=false)]
public partial class spine : opfspinecontent {
    
    private string idField;
    
    private string tocField;
    
    private spinePageprogressiondirection pageprogressiondirectionField;
    
    private bool pageprogressiondirectionFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string toc {
        get {
            return this.tocField;
        }
        set {
            this.tocField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("page-progression-direction")]
    public spinePageprogressiondirection pageprogressiondirection {
        get {
            return this.pageprogressiondirectionField;
        }
        set {
            this.pageprogressiondirectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool pageprogressiondirectionSpecified {
        get {
            return this.pageprogressiondirectionFieldSpecified;
        }
        set {
            this.pageprogressiondirectionFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.idpf.org/2007/opf")]
public enum spinePageprogressiondirection {
    
    /// <remarks/>
    ltr,
    
    /// <remarks/>
    rtl,
    
    /// <remarks/>
    @default,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.idpf.org/2007/opf")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.idpf.org/2007/opf", IsNullable=false)]
public partial class reference {
    
    private string hrefField;
    
    private string typeField;
    
    private string titleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string href {
        get {
            return this.hrefField;
        }
        set {
            this.hrefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.idpf.org/2007/opf")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.idpf.org/2007/opf", IsNullable=false)]
public partial class mediaType {
    
    private string handlerField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string handler {
        get {
            return this.handlerField;
        }
        set {
            this.handlerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.idpf.org/2007/opf")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.idpf.org/2007/opf", IsNullable=false)]
public partial class guide {
    
    private reference[] referenceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("reference")]
    public reference[] reference {
        get {
            return this.referenceField;
        }
        set {
            this.referenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.idpf.org/2007/opf")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.idpf.org/2007/opf", IsNullable=false)]
public partial class bindings {
    
    private mediaType[] mediaTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mediaType")]
    public mediaType[] mediaType {
        get {
            return this.mediaTypeField;
        }
        set {
            this.mediaTypeField = value;
        }
    }
}
