name: Run xsd.exe
on:
  workflow_dispatch:
jobs:
  Xsd:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Tree
      run: |
        Get-ChildItem ".\xsd\epub-test\30\" | ForEach-Object {
          $fn = $_.FullName + "\" + $_.BaseName + ".xsd"
          if(-not( Test-Path -Path $fn )){
            continue
          }
          Start-Process -FilePath "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\xsd.exe" -ArgumentList $fn /classes /language:CS /namespace:kurema.EpubLibrary.Models.Epub30 -outputdir:.\CS\Models\Epub30 -Wait
        }
        tree CS/
      
