name: Run xsd.exe
on:
  workflow_dispatch:
jobs:
  Xsd:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run xsd.exe
      run: |
        Get-ChildItem ".\xsd\epub-test\30\" | ForEach-Object {
          $fn = $_.FullName + "\" + $_.BaseName + ".xsd"
          $outdir = (New-Item -Path "CS\Models\Epub30\$($_.BaseName)" -ItemType Directory -Force).FullName
          $items = """"+((Get-ChildItem $_.FullName -Filter *.xsd) -join """ """)+""""
          if(-not( Test-Path -Path $fn )){
            return
          }
          cmd.exe /c "cd $($_.FullName)&'C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\xsd.exe' $items /classes /language:CS /namespace:kurema.EpubLibrary.Models.Epub30 /outputdir:'${outdir}'"
        }
        tree /f .
      
