name: Make *.xsd files
on:
  workflow_dispatch:
jobs:
  Xsd:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main

    - name: Checkout epubcheck
      uses: actions/checkout@v3
      with:
        repository: w3c/epubcheck
        path: epub
    
    - name: Install trang
      run: |
        sudo apt-get install trang
    
    - name: Run trang
      continue-on-error: true
      run: |
        rm -rf main/xsd/epub-test
        cd epub/src/main/resources/com/adobe/epubcheck/schema/30
        for f in `ls *.rnc`; do mkdir -p ../../../../../../../../../main/xsd/epub-test/${f%.rnc}; trang -I rnc -O xsd $f ../../../../../../../../../main/xsd/epub-test/${f%.rnc}/${f%.rnc}.xsd 2> ../../../../../../../../../main/xsd/epub-test/${f%.rnc}/errors.txt || echo Ignoring error...; done
        
    - name: Git push
      run: |
        cd main
        git config --local user.email "kurema_makoto_software@yahoo.co.jp"
        git config --local user.name "kurema"
        git add --all
        git commit -m "Update xsd/epub-test" -a 
        git pull
        git push origin master
        
