name: Run xsd.exe v2
on:
  workflow_dispatch:
jobs:
  Xsd:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run xsd.exe
      run: |
        cd .\CS\Xml\Epub30
        Remove-Item *.cs
        Get-ChildItem "." -Filter *.xml | ForEach-Object {
          Remove-Item ".\$($_.BaseName)"
          $outdir = (New-Item -Path ".\$($_.BaseName)" -ItemType Directory -Force).FullName
          cmd.exe /c """C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\xsd.exe"" /p:""${_}"" /o:${outdir}"
        }
        cd ..\Epub20
        Remove-Item *.cs
        Get-ChildItem "." -Filter *.xml | ForEach-Object {
          Remove-Item ".\$($_.BaseName)"
          $outdir = (New-Item -Path ".\$($_.BaseName)" -ItemType Directory -Force).FullName
          cmd.exe /c """C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\xsd.exe"" /p:""${_}"" /o:${outdir}"
        }        
    - name: Git it!
      shell: bash
      run: |
        git config --local user.email "kurema_makoto_software@yahoo.co.jp"
        git config --local user.name "kurema"
        git add --all
        git commit -m "Run xsd.exe" -a 
        git pull
        git push origin master        
